#!/bin/bash

MOLECULE_CONF_DIR=molecule.d
CMD="molecule test"

function show_help {
    echo "Run molecule test for all configs found in $MOLECULE_CONF_DIR"
    echo "Usage: $0 [arguments]"
    echo
    echo "Arguments:"
    echo "    --all   Run all CI tests"
    echo "    --help  This help message"
}

function running_in_docker_container {
    if [[ -e /proc/1/cgroup ]]; then
        if [[ $(cat /proc/1/cgroup | grep docker) == 0 ]]; then
            echo "docker"
        fi
    fi

    echo "none"
}

if [[ $(running_in_docker_container) != "none" ]]; then
    echo "$0 seems to be running inside a docker container. This script"
    echo "should run on your local machine for testing CI."

    exit 0
fi

run_count="single"
case $1 in
    "--all")
        CMD="tox"
        run_count="all"
        ;;
    "--help")
        show_help $0
        exit 0
        ;;
    *)
        echo "single!"
        CMD="tox"
        config="$1"
        ;;
esac

MOLECULE_CONFIG=molecule.yml

if [[ "$run_count" == "single" ]]; then
    MOLECULE_SRC_CONFIG=$MOLECULE_CONF_DIR/${config://}.yml
    echo "Using config: $MOLECULE_SRC_CONFIG and linking to: $MOLECULE_CONFIG"
    ln -sf $MOLECULE_SRC_CONFIG $MOLECULE_CONFIG
    $CMD
else
    for platform in $MOLECULE_CONF_DIR/*; do
        echo "Platform: $platform"
        for config in $platform/*; do
            echo "Using config: $config"
            ln -sf $config MOLECULE_CONFIG
            $CMD
        done
    done
fi

rm molecule.yml
